services:
  postgres:
    image: index.docker.io/library/postgres@sha256:06cad38a5d9f5d24b4d83d86def30795d5e4b757fedbf5281172b576dedcd941
    environment:
      POSTGRES_USER: dawgs
      POSTGRES_PASSWORD: weneedbetterpasswords
      POSTGRES_DB: dawgs
    ports:
      - "65432:5432"
    volumes:
      - pg_data:/var/lib/postgresql

  neo4j:
    image: neo4j:4.4.42
    environment:
      NEO4J_AUTH: neo4j/weneedbetterpasswords
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - neo4j_data:/data

volumes:
  pg_data:
  neo4j_data:
