package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/specterops/dawgs/tools/metrics/internal/metrics"
)

func main() {
	var (
		sourceRoot     string
		coverProfile   string
		ignorePattern  string
		textOutputPath string
		jsonOutputPath string
		htmlOutputPath string
		topRecords     int
		crapOver       float64
		cycloOver      int
		failCRAPOver   float64
		printStdout    bool
	)

	flag.StringVar(&sourceRoot, "source-root", ".", "source root to scan for Go functions")
	flag.StringVar(&coverProfile, "coverprofile", "", "Go coverage profile generated by go test")
	flag.StringVar(&ignorePattern, "ignore", "", "regular expression for source files to ignore")
	flag.StringVar(&textOutputPath, "text", "", "path to write the text CRAP report")
	flag.StringVar(&jsonOutputPath, "json", "", "path to write the JSON CRAP report")
	flag.StringVar(&htmlOutputPath, "html", "", "path to write the standalone HTML metrics report")
	flag.IntVar(&topRecords, "top", 20, "maximum number of CRAP records to print in the text report; 0 prints all")
	flag.Float64Var(&crapOver, "over", 0, "only print functions with CRAP greater than this value in the text report")
	flag.IntVar(&cycloOver, "cyclo-over", 0, "complexity threshold used by the HTML report")
	flag.Float64Var(&failCRAPOver, "fail-over", 0, "fail if any function has CRAP greater than this value; 0 disables enforcement")
	flag.BoolVar(&printStdout, "stdout", true, "print the text report to stdout")
	flag.Parse()

	report, err := metrics.Analyze(metrics.Options{
		SourceRoot:   sourceRoot,
		CoverProfile: coverProfile,
		Ignore:       ignorePattern,
	})
	if err != nil {
		fatal(err)
	}

	textOptions := metrics.TextOptions{
		Top:      topRecords,
		CRAPOver: crapOver,
	}

	if textOutputPath != "" {
		if err := writeTextReport(textOutputPath, report, textOptions); err != nil {
			fatal(err)
		}
	}

	if jsonOutputPath != "" {
		if err := writeJSONReport(jsonOutputPath, report); err != nil {
			fatal(err)
		}
	}

	if htmlOutputPath != "" {
		if err := writeHTMLReport(htmlOutputPath, report, metrics.HTMLReportOptions{
			Top:       topRecords,
			CRAPOver:  crapOver,
			CycloOver: cycloOver,
		}); err != nil {
			fatal(err)
		}
	}

	if printStdout {
		if err := metrics.WriteText(os.Stdout, report, textOptions); err != nil {
			fatal(err)
		}
	}

	if records := metrics.RecordsOverCRAPThreshold(report, failCRAPOver); len(records) > 0 {
		for _, record := range records {
			fmt.Fprintf(os.Stderr, "CRAP %.2f exceeds %.2f: %s.%s %s:%d\n",
				record.CRAP,
				failCRAPOver,
				record.Package,
				record.Function,
				record.File,
				record.Line,
			)
		}

		os.Exit(1)
	}
}

func writeTextReport(path string, report metrics.Report, options metrics.TextOptions) error {
	output, err := metrics.CreateOutput(path)
	if err != nil {
		return err
	}
	defer output.Close()

	return metrics.WriteText(output, report, options)
}

func writeJSONReport(path string, report metrics.Report) error {
	output, err := metrics.CreateOutput(path)
	if err != nil {
		return err
	}
	defer output.Close()

	return metrics.WriteJSON(output, report)
}

func writeHTMLReport(path string, report metrics.Report, options metrics.HTMLReportOptions) error {
	output, err := metrics.CreateOutput(path)
	if err != nil {
		return err
	}
	defer output.Close()

	return metrics.WriteHTML(output, report, options)
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
